---
extends: default

rules:
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  comments-indentation: false
  comments:
    level: warning
    min-spaces-from-content: 1
  line-length: disable
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
